# Generated by Django 5.2.6 on 2025-09-09 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('staff', 'Staff'), ('guest', 'Guest')], max_length=10)),
                ('department', models.CharField(choices=[('cs', 'Computer Science'), ('it', 'Information Technology'), ('ml', 'Machine Learning'), ('ee', 'Electronics Engineering'), ('ce', 'Civil Engineering'), ('mba', 'MBA'), ('bba', 'BBA'), ('mca', 'MCA'), ('bca', 'BCA'), ('none', 'None')], default='none', max_length=50)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
