# Generated by Django 5.2.6 on 2025-10-21 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_menuitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Placed', 'Order Placed'), ('Preparing', 'In the Kitchen'), ('Ready', 'Ready for Pickup'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Placed', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('order_id_display', models.CharField(blank=True, max_length=20, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
